dist: precise
# sudo: required
# group: stable
language: php

php:
  - '5.6'
  - '7.1'

services:
  - docker
  - mysql

git:
  quiet: true

before_install:
  - sudo curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

install:
  - sudo chmod +x docker-compose.yml
  - docker-compose up -d
  # - wget -qO ee rt.cx/ee && sudo bash ee
  # - sudo ee stack install --web

before_script:
  # - docker exec -i $(docker-compose ps -q db) mysql -u root -pwordpress -D wordpress < wordpress.sql

script:
  - ls -1
  - docker ps
  - docker exec -i travistest_db_1  mysql -uwordpress -pwordpress wordpress < wordpress.sql
  # - sudo ee site create automation.give.test --wp --user=admin --pass=admin
  # - cd /var/www/automation.give.test/htdocs/
  # - sudo chmod 777 -R ./
  # - cd /var/www/automation.give.test/htdocs/wp-content/plugins/
  # - git clone -b $TRAVIS_BRANCH --single-branch https://github.com/Sidsector9/Travis-Test.git
  # - ls -1
  # - php --version