dist: trusty
language: php
sudo: required
group: edge

php:
  - '5.6'
  - '7.1'

services:
  - docker
  - mysql

git:
  quiet: true

before_install:
  - sudo chmod +x docker-compose.yml

before_script:

script:
  - docker-compose up -d
  - docker exec -i travistest_db_1  mysql -uwordpress -pwordpress wordpress < wordpress.sql