dist: precise
language: php
sudo: required
php:
  - '5.3'
  - '7.1'

services:
  - docker

addons:
  hosts:
    - automation.give.test

git:
  quiet: true

install:
  - docker-compose up -d
  # - wget -qO ee rt.cx/ee && sudo bash ee
  # - sudo ee stack install --web

script:
  # - sudo ee site create automation.give.test --wp --user=admin --pass=admin
  # - cd /var/www/automation.give.test/htdocs/
  # - sudo chmod 777 -R ./
  # - cd /var/www/automation.give.test/htdocs/wp-content/plugins/
  # - git clone -b $TRAVIS_BRANCH --single-branch https://github.com/Sidsector9/Travis-Test.git
  # - ls -1
  # - php --version