dist: trusty
language: php
sudo: required
group: edge

php:
  - '5.6'
  - '7.1'

services:
  - docker
  - mysql

git:
  quiet: true

before_install:
  - sudo chmod +x docker-compose.yml

before_script:
  # run docker containers
  - docker-compose up -d
  # wait for MySQL to become available
  - |
    until docker exec travistest_db_1 mysql -uwordpress -pwordpress wordpress -e "SELECT 1" > /dev/null; do
      >&2 echo "MySQL localhost:3306 for user wordpress is unavailable - sleeping"
      sleep 1
    done
    >&2 echo "MySQL localhost:3306 is up"

script:
  # - docker-compose up -d
  - echo "============"
  - docker exec -i docker-wordpress_db_1  mysql -uroot -pwordpress wordpress -e "SHOW TABLES;"
  - echo "xxxxxxxxxxxx"
  - docker exec -i travistest_db_1  mysql -uwordpress -pwordpress wordpress < wordpress.sql
  - docker exec -i docker-wordpress_db_1  mysql -uroot -pwordpress wordpress -e "SHOW TABLES;"