dist: trusty
language: php
sudo: required
php:
  - '5.6'
  - '7.1'

install:
  # - wget -qO ee rt.cx/ee && sudo bash ee
  # - sudo ee stack install --web

script:
  - echo $TRAVIS_BRANCH
  - git clone -b $TRAVIS_BRANCH --single-branch https://github.com/Sidsector9/Travis-Test.git .
  - git log --oneline
  # - sudo ee site create automation.give.test --wp --user=admin --pass=admin
  # - cd /var/www/automation.give.test/htdocs/
  # - sudo chmod 777 -R ./
  # - cd /var/www/automation.give.test/htdocs/wp-content/plugins/